algoritmo "semnome"
// Função :
// Autor :
// Data : 16/04/2018
// Seção de Declarações 
var
   idade:inteiro
   altura: real
   nome: caractere
   competir:logico

inicio
Escreva("Digite sua Idade: ")
Leia(idade)
Escreva("Digite sua altura: ")
leia(altura)
Escreva("Digite o seu nome: ")
Leia(nome)

competir <- ((idade >=18) e (altura>=1.75))

escreval (nome, " Pode particiar da competicão?",competir)


fimalgoritmo
