Algoritmo "condicionalIdade"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/06/2020
Var
idade: inteiro
resp: caracter

Inicio
//entrada
escreval("Qual sua idade: ")
leia(idade)

escreval("Possui habilitação: ")
leia(resp)

//decisão

se ((idade>=18) e (resp="sim")) entao


     escreval("Pode Passar!")
      

senao

     escreval("Não pode Passar!")
     
fimse



Fimalgoritmo